// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.

var staticCacheName = 'transportation-v2';

self.addEventListener('install', function(event) {
    console.log('install');
    event.waitUntil(
      caches.open(staticCacheName).then(function(cache) {
        return cache.addAll([
          '/',
          '/styles/materialize.css',
          'images/waiting.png',
          'images/crow_fly.png',
          'images/public_transport.png',
          'images/street_network.png',
          'images/walking.png',
          '/styles/main.css',
          '/scripts/main.min.js',
          'https://fonts.googleapis.com/icon?family=Material+Icons',
          'fonts/roboto/Roboto-Regular.woff',
          'fonts/roboto/Roboto-Regular.woff2',
          'fonts/roboto/Roboto-Regular.ttf'
        ]);
      })
    );
});

self.addEventListener('fetch', function(event) {
    event.respondWith(
      caches.match(event.request).then(function(response) {
        if (response) return response;
        return fetch(event.request);
      })
    );
});

self.addEventListener('activate', function(event) {
    event.waitUntil(
        caches.keys().then(function(cacheNames) {
          return Promise.all(
            cacheNames.filter(function(cacheName) {
              return cacheName.startsWith('transportation-') &&
                     cacheName != staticCacheName;
            }).map(function(cacheName) {
              return caches.delete(cacheName);
            })
          );
        })
    );
});