// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.

self.addEventListener('install', function(event) {
    console.log('install');
    event.waitUntil(
      caches.open('transportation-v1').then(function(cache) {
        return cache.addAll([
          '/',
          '/styles/materialize.css',
          'images/waiting.png',
          'images/crow_fly.png',
          'images/public_transport.png',
          'images/walking.png',
          '/styles/main.css',
          '/scripts/main.min.js',
          'https://fonts.googleapis.com/icon?family=Material+Icons',
        ]);
      })
    );
});

self.addEventListener('fetch', function(event) {

    event.respondWith(
      caches.match(event.request).then(function(response) {
        if (response) return response;
        return fetch(event.request);
      })

      // fetch(event.request).then(function(response) {
      //   if (response.status == 404) {
      //       return new Response("Whoops, not found");
      //   }
      //   return response;
      // }).catch(function() {
      //   return new Response('Uh oh, that totally failed"');
      // });
    // );
    );
});